apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: flux
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31730 # You can customize this port
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: flux
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31500 # choose a port in the 30000–32767 range
