apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: flux
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: localhost  # Use localhost for local development
      http:
        paths:
          - path: /frontend/?(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000  # Updated to 3000 for frontend service
          - path: /backend/?(.*)
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 5000
