name: CI/CD to Docker Hub and ArgoCD

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin

    - name: Set image tag
      id: vars
      run: echo "TAG=${GITHUB_SHA}" >> "$GITHUB_ENV"

    - name: Build and push backend image
      run: |
        docker build -t $DOCKERHUB_USERNAME/flux-backend:${TAG} ./backend
        docker push $DOCKERHUB_USERNAME/flux-backend:${TAG}

    - name: Build and push frontend image
      run: |
        docker build -t $DOCKERHUB_USERNAME/flux-frontend:${TAG} ./frontend/myapp
        docker push $DOCKERHUB_USERNAME/flux-frontend:${TAG}

    - name: Clone GitOps repo
      run: |
        git clone https://${{ secrets.GITOPS_REPO_TOKEN }}@${{ secrets.GITOPS_REPO_URL#https:// }} gitops
        cd gitops
        git config user.name "${{ secrets.GITOPS_REPO_USERNAME }}"
        git config user.email "${{ secrets.GITOPS_REPO_EMAIL }}"

    - name: Update Helm values in GitOps repo
      run: |
        cd gitops/helm/your-app
        yq e -i ".backend.tag = \"$TAG\"" values.yaml
        yq e -i ".frontend.tag = \"$TAG\"" values.yaml
        git add values.yaml
        git commit -m "Update image tags to $TAG"
        git push
